#!/usr/bin/env python3
"""
AWS Lambda Function for Content Aggregator

This module contains the Lambda function handler that will be invoked by EventBridge
to generate and send the content digest.

NOTE: This Lambda function is DEPRECATED. 
Use the Step Functions workflow (ContentAggregatorWorkflow) instead.
"""

import os
import json
import logging
from datetime import datetime
import boto3
import sys

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def fetch_and_process_content(aggregator, days, category):
    """Fetch and process content from all sources."""
    all_content = aggregator.fetch_rss_content() + aggregator.fetch_github_content()
    
    try:
        if hasattr(aggregator, 'summarizer') and aggregator.summarizer:
            all_content = aggregator.summarizer.batch_summarize(all_content)
            for item in all_content:
                if item.get('generated_summary'):
                    item['ai_summary'] = item['generated_summary']
    except Exception as e:
        logger.error(f"Error summarizing content: {e}")
    
    all_content = aggregator.deduplicate_content(all_content)
    if category:
        all_content = aggregator.filter_content_by_category(all_content, category)
    all_content = aggregator.filter_content_by_date(all_content, int(days))
    
    for item in all_content:
        item['relevance_score'] = calculate_relevance_score(item)
    
    return all_content

def generate_digest(all_content, max_items):
    """Generate plain text digest from content."""
    q_related_items = [item for item in all_content if item['relevance_score'] >= 30]
    competitor_items = [item for item in all_content if any(kw in (item.get('title', '') + ' ' + item.get('summary', '')).lower() for kw in ['github copilot', 'anthropic claude', 'openai', 'gpt', 'bard', 'gemini'])]
    
    text_lines = ["YOUR DAILY CONTENT DIGEST", datetime.now().strftime('%A, %B %d, %Y'), "=" * 60, ""]
    
    if q_related_items:
        text_lines.extend(["AMAZON Q & CODING ASSISTANT HIGHLIGHTS", "-" * 40])
        for item in q_related_items[:int(max_items)]:
            text_lines.extend([f"* {item['title']} [Relevance: {item['relevance_score']}]", f"  Source: {item['source']}", f"  Link: {item['link']}", ""])
    
    text_lines.extend(["=" * 60, "This digest was generated by Content Aggregator."])
    return "\n".join(text_lines)

def lambda_handler(event, context):
    """AWS Lambda function handler."""
    try:
        logger.info("Content Aggregator Lambda function invoked")
        
        params = event.get('params', {})
        email = params.get('email', os.environ.get('RECIPIENT_EMAIL'))
        days = params.get('days', os.environ.get('DAYS', '7'))
        max_items = params.get('max_items', os.environ.get('MAX_ITEMS', '10'))
        category = params.get('category', os.environ.get('CATEGORY', ''))
        
        if not email:
            raise ValueError("Recipient email is required")
        
        sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        from backend.core.aggregator import ContentAggregator
        from backend.core.email_digest.email_sender import EmailSender
        
        aggregator = ContentAggregator(enable_summarization=False)
        all_content = fetch_and_process_content(aggregator, days, category)
        digest_content = generate_digest(all_content, max_items)
        
        sender = EmailSender()
        response = sender.send_digest(email, "Your Daily Content Digest", digest_content)
        
        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': 'Content digest generated and sent successfully',
                'timestamp': datetime.now().isoformat(),
                'recipient': email,
                'items_count': len(all_content)
            })
        }
        
    except Exception as e:
        logger.error(f"Error in Lambda function: {e}", exc_info=True)
        return {
            'statusCode': 500,
            'body': json.dumps({
                'message': f'Error generating or sending content digest: {str(e)}',
                'timestamp': datetime.now().isoformat()
            })
        }

def calculate_relevance_score(item):
    """
    Calculate a relevance score for an item based on Q-related keywords.
    Higher score means more relevant to Amazon Q.
    
    Args:
        item (dict): Content item to score
        
    Returns:
        int: Relevance score (0-100)
    """
    keyword_scores = {
        'amazon q': (50, 30), 'q developer': (50, 30), 'codewhisperer': (50, 30),
        'coding assistant': (30, 20), 'ai pair programming': (30, 20), 'code generation': (30, 20),
        'generative ai': (15, 10), 'llm': (15, 10), 'large language model': (15, 10), 'ai coding': (15, 10),
        'github copilot': (25, 15), 'anthropic claude': (25, 15), 'openai': (25, 15), 'gpt': (25, 15), 'bard': (25, 15), 'gemini': (25, 15)
    }
    
    title = item.get('title', '').lower() if item.get('title') is not None else ''
    summary = item.get('summary', '').lower() if item.get('summary') is not None else ''
    
    score = 0
    for keyword, (title_score, summary_score) in keyword_scores.items():
        if keyword in title:
            score += title_score
        elif keyword in summary:
            score += summary_score
    
    return min(score, 100)

# For local testing
if __name__ == "__main__":
    test_event = {
        'params': {
            'email': 'your.email@example.com',
            'days': '1',
            'max_items': '3'
        }
    }
    print(lambda_handler(test_event, None))
